name: cqbpy
channels:
  - conda-forge
  - nodefaults
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - icu=78.2=h33c6efd_0
  - ld_impl_linux-64=2.45.1=default_hbd61a6d_101
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h3435931_0
  - libgcc=15.2.0=he0feb66_17
  - libgcc-ng=15.2.0=h69a702a_17
  - libgomp=15.2.0=he0feb66_17
  - liblzma=5.8.2=hb03c661_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.2=hf4e2dac_0
  - libstdcxx=15.2.0=h934c35e_17
  - libuuid=2.41.3=h5347b49_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.1=h35e630c_1
  - packaging=26.0=pyhcf101f3_0
  - pip=26.0.1=pyh8b19718_0
  - python=3.12.12=hd63d673_2_cpython
  - readline=8.3=h853b02a_0
  - setuptools=82.0.0=pyh332efcf_0
  - tk=8.6.13=noxft_h366c992_103
  - tzdata=2025c=hc9c84f9_1
  - wheel=0.46.3=pyhd8ed1ab_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - bm3d==4.0.3
      - bm4d==4.2.5
      - contourpy==1.3.3
      - cycler==0.12.1
      - fonttools==4.61.1
      - h5py==3.15.1
      - imageio==2.37.2
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - llvmlite==0.46.0
      - matplotlib==3.10.8
      - networkx==3.6.1
      - numba==0.63.1
      - numpy==2.3.5
      - opencv-python==4.13.0.92
      - pillow==12.1.1
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - pywavelets==1.9.0
      - scikit-image==0.26.0
      - scipy==1.17.0
      - six==1.17.0
      - tifffile==2026.1.28
